spring.application.name=stock-dashboard

#spring:
#kafka:
#bootstrap-servers: localhost:9092
#consumer:
#group-id: stock-group
#auto-offset-reset: earliest

#app
spring.datasource.url=jdbc:h2:mem:stockdb
spring.datasource.driver-class-name=org.h2.Driver
spring.jpa.hibernate.ddl-auto=create-drop
spring.h2.console.enabled=true

#Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379

#Jwt secret
jwt.secret=mySuperSecretKeyForJwtAuthentication123456789

#Alpha Vantage API key
#alphavantage.api.key=7F06FT4CUTDM1KDT
alphavantage.api.key=FZH0B989VQ6B051N
alphavantage.base.url=https://www.alphavantage.co/query

#Cache TTLs (used by RedisConfig)
cache.stock.price.ttl=2
cache.stock.history.ttl=10
cache.recommendation.ttl=5

# Alpha Vantage free tier is 5 req/min ? log when you hit it
logging.level.com.stock.service=DEBUG

# H2 console (useful for debugging portfolio data)
#spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
